### ISSUE TITLE
add android demo and tutorial?

### ISSUE THREAD

**Issue by buhe** [meetwudi/EmbededReactNativeExample#2]
add android demo and tutorial?

Thanks.

**Comment by meetwudi** [comment]
I am not familiar with Android though. Would be better to investigate
later, or see if someone is interested then I can accept PR :)

buhe notifications@github.com于2015年10月16日 周五下午8:31写道：

**Comment by buhe** [comment]
ok , I will be research it  :)

**Comment by meetwudi** [comment]
Actually I don't see it's necessary to merge Android example in this repo.
Feel free to set up new repo if you want.

buhe notifications@github.com于2015年10月16日 周五下午8:53写道：

> ok , I will be research it :)
>
